Search.appendIndex(
    [
                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegAnimatedGif",
            "name": "FFMpegAnimatedGif",
            "summary": "Serves\u0020as\u0020a\u0020compatibility\u0020adapter\u0020for\u0020old\u0020ffmpeg\u002Dphp\u0020extension.",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegAnimatedGif.html"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegAnimatedGif\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegAnimatedGif.html#method___construct"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegAnimatedGif\u003A\u003AaddFrame\u0028\u0029",
            "name": "addFrame",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegAnimatedGif.html#method_addFrame"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegAnimatedGif\u003A\u003A__clone\u0028\u0029",
            "name": "__clone",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegAnimatedGif.html#method___clone"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegAnimatedGif\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegAnimatedGif.html#method___destruct"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegAnimatedGif\u003A\u003A\u0024adaptee",
            "name": "adaptee",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegAnimatedGif.html#property_adaptee"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegFrame",
            "name": "FFMpegFrame",
            "summary": "Serves\u0020as\u0020a\u0020compatibility\u0020adapter\u0020for\u0020old\u0020ffmpeg\u002Dphp\u0020extension.",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegFrame.html"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegFrame\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegFrame.html#method___construct"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegFrame\u003A\u003AgetWidth\u0028\u0029",
            "name": "getWidth",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegFrame.html#method_getWidth"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegFrame\u003A\u003AgetHeight\u0028\u0029",
            "name": "getHeight",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegFrame.html#method_getHeight"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegFrame\u003A\u003AgetPTS\u0028\u0029",
            "name": "getPTS",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegFrame.html#method_getPTS"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegFrame\u003A\u003AgetPresentationTimestamp\u0028\u0029",
            "name": "getPresentationTimestamp",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegFrame.html#method_getPresentationTimestamp"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegFrame\u003A\u003Aresize\u0028\u0029",
            "name": "resize",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegFrame.html#method_resize"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegFrame\u003A\u003Acrop\u0028\u0029",
            "name": "crop",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegFrame.html#method_crop"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegFrame\u003A\u003AtoGDImage\u0028\u0029",
            "name": "toGDImage",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegFrame.html#method_toGDImage"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegFrame\u003A\u003A__clone\u0028\u0029",
            "name": "__clone",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegFrame.html#method___clone"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegFrame\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegFrame.html#method___destruct"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegFrame\u003A\u003A\u0024adaptee",
            "name": "adaptee",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegFrame.html#property_adaptee"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie",
            "name": "FFMpegMovie",
            "summary": "Serves\u0020as\u0020a\u0020compatibility\u0020adapter\u0020for\u0020old\u0020ffmpeg\u002Dphp\u0020extension.",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method___construct"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetDuration\u0028\u0029",
            "name": "getDuration",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getDuration"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetFrameCount\u0028\u0029",
            "name": "getFrameCount",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getFrameCount"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetFrameRate\u0028\u0029",
            "name": "getFrameRate",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getFrameRate"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetFilename\u0028\u0029",
            "name": "getFilename",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getFilename"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetComment\u0028\u0029",
            "name": "getComment",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getComment"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getTitle"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetArtist\u0028\u0029",
            "name": "getArtist",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getArtist"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetAuthor\u0028\u0029",
            "name": "getAuthor",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getAuthor"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetCopyright\u0028\u0029",
            "name": "getCopyright",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getCopyright"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetGenre\u0028\u0029",
            "name": "getGenre",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getGenre"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetTrackNumber\u0028\u0029",
            "name": "getTrackNumber",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getTrackNumber"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetYear\u0028\u0029",
            "name": "getYear",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getYear"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetFrameHeight\u0028\u0029",
            "name": "getFrameHeight",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getFrameHeight"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetFrameWidth\u0028\u0029",
            "name": "getFrameWidth",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getFrameWidth"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetPixelFormat\u0028\u0029",
            "name": "getPixelFormat",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getPixelFormat"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetPixelAspectRatio\u0028\u0029",
            "name": "getPixelAspectRatio",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getPixelAspectRatio"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetBitRate\u0028\u0029",
            "name": "getBitRate",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getBitRate"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetVideoBitRate\u0028\u0029",
            "name": "getVideoBitRate",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getVideoBitRate"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetAudioBitRate\u0028\u0029",
            "name": "getAudioBitRate",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getAudioBitRate"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetAudioSampleRate\u0028\u0029",
            "name": "getAudioSampleRate",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getAudioSampleRate"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetFrameNumber\u0028\u0029",
            "name": "getFrameNumber",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getFrameNumber"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetVideoCodec\u0028\u0029",
            "name": "getVideoCodec",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getVideoCodec"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetAudioCodec\u0028\u0029",
            "name": "getAudioCodec",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getAudioCodec"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetAudioChannels\u0028\u0029",
            "name": "getAudioChannels",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getAudioChannels"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AhasAudio\u0028\u0029",
            "name": "hasAudio",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_hasAudio"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AhasVideo\u0028\u0029",
            "name": "hasVideo",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_hasVideo"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetFrame\u0028\u0029",
            "name": "getFrame",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getFrame"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003AgetNextKeyFrame\u0028\u0029",
            "name": "getNextKeyFrame",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method_getNextKeyFrame"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003A__clone\u0028\u0029",
            "name": "__clone",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method___clone"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003A__destruct\u0028\u0029",
            "name": "__destruct",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#method___destruct"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters\\FFMpegMovie\u003A\u003A\u0024adaptee",
            "name": "adaptee",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Adapters-FFMpegMovie.html#property_adaptee"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif",
            "name": "AnimatedGif",
            "summary": "AnimatedGif\u0020represents\u0020an\u0020animated\u0020gif\u0020object.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020new\u0020AnimatedGif\u0020object.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#method___construct"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003AaddFrame\u0028\u0029",
            "name": "addFrame",
            "summary": "Add\u0020a\u0020frame\u0020to\u0020the\u0020end\u0020of\u0020the\u0020animated\u0020gif.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#method_addFrame"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003AaddGifHeader\u0028\u0029",
            "name": "addGifHeader",
            "summary": "Adding\u0020header\u0020to\u0020the\u0020animation.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#method_addGifHeader"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003AaddFrameData\u0028\u0029",
            "name": "addFrameData",
            "summary": "Adding\u0020frame\u0020binary\u0020data\u0020to\u0020the\u0020animation.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#method_addFrameData"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003AaddGifFooter\u0028\u0029",
            "name": "addGifFooter",
            "summary": "Adding\u0020footer\u0020to\u0020the\u0020animation.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#method_addGifFooter"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003AgetGifWord\u0028\u0029",
            "name": "getGifWord",
            "summary": "Gif\u0020integer\u0020wrapper.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#method_getGifWord"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003AgifBlockCompare\u0028\u0029",
            "name": "gifBlockCompare",
            "summary": "Gif\u0020compare\u0020block.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#method_gifBlockCompare"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003Asave\u0028\u0029",
            "name": "save",
            "summary": "Saving\u0020animated\u0020gif\u0020to\u0020remote\u0020file.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#method_save"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003AgetAnimation\u0028\u0029",
            "name": "getAnimation",
            "summary": "Getting\u0020animation\u0020binary\u0020data.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#method_getAnimation"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "String\u0020representation\u0020of\u0020an\u0020AnimatedGif.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#method_serialize"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003Aunserialize\u0028\u0029",
            "name": "unserialize",
            "summary": "Constructs\u0020the\u0020AnimatedGif.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#method_unserialize"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003A\u0024outFilePath",
            "name": "outFilePath",
            "summary": "Location\u0020in\u0020the\u0020filesystem\u0020where\u0020the\u0020animated\u0020gif\u0020will\u0020be\u0020written.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#property_outFilePath"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003A\u0024width",
            "name": "width",
            "summary": "Width\u0020of\u0020the\u0020animated\u0020gif.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#property_width"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003A\u0024height",
            "name": "height",
            "summary": "Height\u0020of\u0020the\u0020animated\u0020gif.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#property_height"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003A\u0024frameRate",
            "name": "frameRate",
            "summary": "Frame\u0020rate\u0020of\u0020the\u0020animated\u0020gif\u0020in\u0020frames\u0020per\u0020second.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#property_frameRate"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003A\u0024loopCount",
            "name": "loopCount",
            "summary": "Number\u0020of\u0020times\u0020to\u0020loop\u0020the\u0020animation.\u0020Put\u0020a\u0020zero\u0020here\u0020to\u0020loop\u0020forever\u0020or\u0020omit\u0020this\u0020parameter\u0020to\u0020disable\u0020looping.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#property_loopCount"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003A\u0024frames",
            "name": "frames",
            "summary": "Binary\u0020data\u0020of\u0020gif\u0020files\u0020to\u0020create\u0020animation.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#property_frames"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003A\u0024gifData",
            "name": "gifData",
            "summary": "Gif\u0020binary\u0020data\u0020of\u0020animation.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#property_gifData"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\AnimatedGif\u003A\u003A\u0024counter",
            "name": "counter",
            "summary": "Counter\u0020of\u0020first\u0020animation.",
            "url": "classes/Char0n-FFMpegPHP-AnimatedGif.html#property_counter"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame",
            "name": "Frame",
            "summary": "Represents\u0020one\u0020frame\u0020from\u0020the\u0020movie.",
            "url": "classes/Char0n-FFMpegPHP-Frame.html"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Create\u0020a\u0020Frame\u0020object\u0020from\u0020a\u0020GD\u0020image.",
            "url": "classes/Char0n-FFMpegPHP-Frame.html#method___construct"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame\u003A\u003AgdImageToBinaryData\u0028\u0029",
            "name": "gdImageToBinaryData",
            "summary": "Transforms\u0020gdImage\u0020resource\u0020to\u0020binary\u0020data.",
            "url": "classes/Char0n-FFMpegPHP-Frame.html#method_gdImageToBinaryData"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame\u003A\u003AgetPresentationTimestamp\u0028\u0029",
            "name": "getPresentationTimestamp",
            "summary": "Return\u0020the\u0020presentation\u0020time\u0020stamp\u0020of\u0020the\u0020frame.",
            "url": "classes/Char0n-FFMpegPHP-Frame.html#method_getPresentationTimestamp"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame\u003A\u003AgetPTS\u0028\u0029",
            "name": "getPTS",
            "summary": "Return\u0020the\u0020presentation\u0020time\u0020stamp\u0020of\u0020the\u0020frame\u003B\u0020alias\u0020\u0024frame\u002D\u003EgetPresentationTimestamp\u0028\u0029.",
            "url": "classes/Char0n-FFMpegPHP-Frame.html#method_getPTS"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame\u003A\u003Acrop\u0028\u0029",
            "name": "crop",
            "summary": "Crop\u0020the\u0020frame.",
            "url": "classes/Char0n-FFMpegPHP-Frame.html#method_crop"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame\u003A\u003Aresize\u0028\u0029",
            "name": "resize",
            "summary": "Resize\u0020and\u0020optionally\u0020crop\u0020the\u0020frame.\u0020\u0028Cropping\u0020is\u0020built\u0020into\u0020ffmpeg\u0020resizing\u0020so\u0020I\u0027m\u0020providing\u0020it\u0020here\u0020for\ncompleteness.\u0029",
            "url": "classes/Char0n-FFMpegPHP-Frame.html#method_resize"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame\u003A\u003AtoGDImage\u0028\u0029",
            "name": "toGDImage",
            "summary": "Returns\u0020a\u0020truecolor\u0020GD\u0020image\u0020of\u0020the\u0020frame.",
            "url": "classes/Char0n-FFMpegPHP-Frame.html#method_toGDImage"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame\u003A\u003AgetWidth\u0028\u0029",
            "name": "getWidth",
            "summary": "Return\u0020the\u0020width\u0020of\u0020the\u0020frame.",
            "url": "classes/Char0n-FFMpegPHP-Frame.html#method_getWidth"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame\u003A\u003AgetHeight\u0028\u0029",
            "name": "getHeight",
            "summary": "Return\u0020the\u0020height\u0020of\u0020the\u0020frame.",
            "url": "classes/Char0n-FFMpegPHP-Frame.html#method_getHeight"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "Return\u0020string\u0020representation\u0020of\u0020a\u0020Frame.",
            "url": "classes/Char0n-FFMpegPHP-Frame.html#method_serialize"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame\u003A\u003Aunserialize\u0028\u0029",
            "name": "unserialize",
            "summary": "Constructs\u0020the\u0020Frame\u0020from\u0020serialized\u0020data.",
            "url": "classes/Char0n-FFMpegPHP-Frame.html#method_unserialize"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame\u003A\u003A\u0024EX_CODE_NO_VALID_RESOURCE",
            "name": "EX_CODE_NO_VALID_RESOURCE",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Frame.html#property_EX_CODE_NO_VALID_RESOURCE"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame\u003A\u003A\u0024gdImageData",
            "name": "gdImageData",
            "summary": "GdImage\u0020binary\u0020data.",
            "url": "classes/Char0n-FFMpegPHP-Frame.html#property_gdImageData"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame\u003A\u003A\u0024pts",
            "name": "pts",
            "summary": "Presentation\u0020time\u0020stamp.",
            "url": "classes/Char0n-FFMpegPHP-Frame.html#property_pts"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame\u003A\u003A\u0024width",
            "name": "width",
            "summary": "Frame\u0020width\u0020in\u0020pixels.",
            "url": "classes/Char0n-FFMpegPHP-Frame.html#property_width"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Frame\u003A\u003A\u0024height",
            "name": "height",
            "summary": "Frame\u0020height\u0020in\u0020pixels.",
            "url": "classes/Char0n-FFMpegPHP-Frame.html#property_height"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie",
            "name": "Movie",
            "summary": "Represents\u0020a\u0020movie\u0020file.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Open\u0020a\u0020video\u0020or\u0020audio\u0020file\u0020and\u0020return\u0020it\u0020as\u0020an\u0020Movie\u0020object.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method___construct"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AsetProvider\u0028\u0029",
            "name": "setProvider",
            "summary": "Setting\u0020output\u0020provider\u0020implementation.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_setProvider"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetProvider\u0028\u0029",
            "name": "getProvider",
            "summary": "Getting\u0020current\u0020output\u0020provider\u0020implementation.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getProvider"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetDuration\u0028\u0029",
            "name": "getDuration",
            "summary": "Return\u0020the\u0020duration\u0020of\u0020a\u0020movie\u0020or\u0020audio\u0020file\u0020in\u0020seconds.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getDuration"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetFrameCount\u0028\u0029",
            "name": "getFrameCount",
            "summary": "Return\u0020the\u0020number\u0020of\u0020frames\u0020in\u0020a\u0020movie\u0020or\u0020audio\u0020file.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getFrameCount"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetFrameRate\u0028\u0029",
            "name": "getFrameRate",
            "summary": "Return\u0020the\u0020frame\u0020rate\u0020of\u0020a\u0020movie\u0020in\u0020fps.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getFrameRate"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetFilename\u0028\u0029",
            "name": "getFilename",
            "summary": "Return\u0020the\u0020path\u0020and\u0020name\u0020of\u0020the\u0020movie\u0020file\u0020or\u0020audio\u0020file.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getFilename"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetComment\u0028\u0029",
            "name": "getComment",
            "summary": "Return\u0020the\u0020comment\u0020field\u0020from\u0020the\u0020movie\u0020or\u0020audio\u0020file.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getComment"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetTitle\u0028\u0029",
            "name": "getTitle",
            "summary": "Return\u0020the\u0020title\u0020field\u0020from\u0020the\u0020movie\u0020or\u0020audio\u0020file.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getTitle"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetArtist\u0028\u0029",
            "name": "getArtist",
            "summary": "Return\u0020the\u0020author\u0020field\u0020from\u0020the\u0020movie\u0020or\u0020the\u0020artist\u0020ID3\u0020field\u0020from\u0020an\u0020mp3\u0020file\u003B\u0020alias\u0020\u0024movie\u002D\u003EgetArtist\u0028\u0029",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getArtist"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetAuthor\u0028\u0029",
            "name": "getAuthor",
            "summary": "Return\u0020the\u0020author\u0020field\u0020from\u0020the\u0020movie\u0020or\u0020the\u0020artist\u0020ID3\u0020field\u0020from\u0020an\u0020mp3\u0020file.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getAuthor"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetCopyright\u0028\u0029",
            "name": "getCopyright",
            "summary": "Return\u0020the\u0020copyright\u0020field\u0020from\u0020the\u0020movie\u0020or\u0020audio\u0020file.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getCopyright"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetGenre\u0028\u0029",
            "name": "getGenre",
            "summary": "Return\u0020the\u0020genre\u0020ID3\u0020field\u0020from\u0020an\u0020mp3\u0020file.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getGenre"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetTrackNumber\u0028\u0029",
            "name": "getTrackNumber",
            "summary": "Return\u0020the\u0020track\u0020ID3\u0020field\u0020from\u0020an\u0020mp3\u0020file.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getTrackNumber"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetYear\u0028\u0029",
            "name": "getYear",
            "summary": "Return\u0020the\u0020year\u0020ID3\u0020field\u0020from\u0020an\u0020mp3\u0020file.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getYear"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetFrameHeight\u0028\u0029",
            "name": "getFrameHeight",
            "summary": "Return\u0020the\u0020height\u0020of\u0020the\u0020movie\u0020in\u0020pixels.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getFrameHeight"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetFrameWidth\u0028\u0029",
            "name": "getFrameWidth",
            "summary": "Return\u0020the\u0020width\u0020of\u0020the\u0020movie\u0020in\u0020pixels.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getFrameWidth"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetPixelFormat\u0028\u0029",
            "name": "getPixelFormat",
            "summary": "Return\u0020the\u0020pixel\u0020format\u0020of\u0020the\u0020movie.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getPixelFormat"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetPixelAspectRatio\u0028\u0029",
            "name": "getPixelAspectRatio",
            "summary": "Return\u0020the\u0020pixel\u0020aspect\u0020ratio\u0020of\u0020the\u0020movie.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getPixelAspectRatio"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetRotation\u0028\u0029",
            "name": "getRotation",
            "summary": "Return\u0020the\u0020rotation\u0020angle\u0020of\u0020the\u0020movie.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getRotation"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetBitRate\u0028\u0029",
            "name": "getBitRate",
            "summary": "Return\u0020the\u0020bit\u0020rate\u0020of\u0020the\u0020movie\u0020or\u0020audio\u0020file\u0020in\u0020bits\u0020per\u0020second.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getBitRate"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetVideoBitRate\u0028\u0029",
            "name": "getVideoBitRate",
            "summary": "Return\u0020the\u0020bit\u0020rate\u0020of\u0020the\u0020video\u0020in\u0020bits\u0020per\u0020second.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getVideoBitRate"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetAudioBitRate\u0028\u0029",
            "name": "getAudioBitRate",
            "summary": "Return\u0020the\u0020audio\u0020bit\u0020rate\u0020of\u0020the\u0020media\u0020file\u0020in\u0020bits\u0020per\u0020second.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getAudioBitRate"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetAudioSampleRate\u0028\u0029",
            "name": "getAudioSampleRate",
            "summary": "Return\u0020the\u0020audio\u0020sample\u0020rate\u0020of\u0020the\u0020media\u0020file\u0020in\u0020bits\u0020per\u0020second.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getAudioSampleRate"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetFrameNumber\u0028\u0029",
            "name": "getFrameNumber",
            "summary": "Return\u0020the\u0020current\u0020frame\u0020index.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getFrameNumber"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetVideoCodec\u0028\u0029",
            "name": "getVideoCodec",
            "summary": "Return\u0020the\u0020name\u0020of\u0020the\u0020video\u0020codec\u0020used\u0020to\u0020encode\u0020this\u0020movie.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getVideoCodec"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetAudioCodec\u0028\u0029",
            "name": "getAudioCodec",
            "summary": "Return\u0020the\u0020name\u0020of\u0020the\u0020audio\u0020codec\u0020used\u0020to\u0020encode\u0020this\u0020movie.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getAudioCodec"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetAudioChannels\u0028\u0029",
            "name": "getAudioChannels",
            "summary": "Return\u0020the\u0020number\u0020of\u0020audio\u0020channels\u0020in\u0020this\u0020movie.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getAudioChannels"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AhasAudio\u0028\u0029",
            "name": "hasAudio",
            "summary": "Return\u0020boolean\u0020value\u0020indicating\u0020whether\u0020the\u0020movie\u0020has\u0020an\u0020audio\u0020stream.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_hasAudio"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AhasVideo\u0028\u0029",
            "name": "hasVideo",
            "summary": "Return\u0020boolean\u0020value\u0020indicating\u0020whether\u0020the\u0020movie\u0020has\u0020a\u0020video\u0020stream.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_hasVideo"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetFrame\u0028\u0029",
            "name": "getFrame",
            "summary": "Returns\u0020a\u0020frame\u0020from\u0020the\u0020movie\u0020as\u0020an\u0020Frame\u0020object.\u0020Returns\u0020false\u0020if\u0020the\u0020frame\u0020was\u0020not\u0020found.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getFrame"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetFrameAtTime\u0028\u0029",
            "name": "getFrameAtTime",
            "summary": "Returns\u0020a\u0020frame\u0020from\u0020the\u0020movie\u0020as\u0020a\u0020Frame\u0020object.\u0020Returns\u0020false\u0020if\u0020the\u0020frame\u0020was\u0020not\u0020found.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getFrameAtTime"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003AgetNextKeyFrame\u0028\u0029",
            "name": "getNextKeyFrame",
            "summary": "Returns\u0020the\u0020next\u0020key\u0020frame\u0020from\u0020the\u0020movie\u0020as\u0020an\u0020Frame\u0020object.\u0020Returns\u0020false\u0020if\u0020the\u0020frame\u0020was\u0020not\u0020found.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_getNextKeyFrame"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A__clone\u0028\u0029",
            "name": "__clone",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method___clone"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "String\u0020representation\u0020of\u0020a\u0020Movie.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_serialize"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003Aunserialize\u0028\u0029",
            "name": "unserialize",
            "summary": "Constructs\u0020the\u0020Movie\u0020from\u0020serialized\u0020data.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#method_unserialize"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_DURATION",
            "name": "REGEX_DURATION",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_DURATION"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_FRAME_RATE",
            "name": "REGEX_FRAME_RATE",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_FRAME_RATE"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_COMMENT",
            "name": "REGEX_COMMENT",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_COMMENT"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_TITLE",
            "name": "REGEX_TITLE",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_TITLE"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_ARTIST",
            "name": "REGEX_ARTIST",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_ARTIST"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_COPYRIGHT",
            "name": "REGEX_COPYRIGHT",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_COPYRIGHT"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_GENRE",
            "name": "REGEX_GENRE",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_GENRE"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_TRACK_NUMBER",
            "name": "REGEX_TRACK_NUMBER",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_TRACK_NUMBER"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_YEAR",
            "name": "REGEX_YEAR",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_YEAR"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_FRAME_WH",
            "name": "REGEX_FRAME_WH",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_FRAME_WH"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_PIXEL_FORMAT",
            "name": "REGEX_PIXEL_FORMAT",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_PIXEL_FORMAT"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_PIXEL_ASPECT_RATIO",
            "name": "REGEX_PIXEL_ASPECT_RATIO",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_PIXEL_ASPECT_RATIO"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_BITRATE",
            "name": "REGEX_BITRATE",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_BITRATE"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_VIDEO_BITRATE",
            "name": "REGEX_VIDEO_BITRATE",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_VIDEO_BITRATE"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_AUDIO_BITRATE",
            "name": "REGEX_AUDIO_BITRATE",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_AUDIO_BITRATE"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_AUDIO_SAMPLE_RATE",
            "name": "REGEX_AUDIO_SAMPLE_RATE",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_AUDIO_SAMPLE_RATE"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_VIDEO_CODEC",
            "name": "REGEX_VIDEO_CODEC",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_VIDEO_CODEC"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_AUDIO_CODEC",
            "name": "REGEX_AUDIO_CODEC",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_AUDIO_CODEC"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_AUDIO_CHANNELS",
            "name": "REGEX_AUDIO_CHANNELS",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_AUDIO_CHANNELS"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_HAS_AUDIO",
            "name": "REGEX_HAS_AUDIO",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_HAS_AUDIO"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_HAS_VIDEO",
            "name": "REGEX_HAS_VIDEO",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_HAS_VIDEO"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_ROTATION",
            "name": "REGEX_ROTATION",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_ROTATION"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024REGEX_ERRORS",
            "name": "REGEX_ERRORS",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_REGEX_ERRORS"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024ffmpegBinary",
            "name": "ffmpegBinary",
            "summary": "Path\u0020to\u0020\u0060ffmpeg\u0060\u0020binary.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_ffmpegBinary"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024provider",
            "name": "provider",
            "summary": "Output\u0020provider\u0020instance.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_provider"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024movieFile",
            "name": "movieFile",
            "summary": "Movie\u0020file\u0020path",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_movieFile"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024output",
            "name": "output",
            "summary": "Output\u0020providers\u0020output\u0020as\u0020string.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_output"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024duration",
            "name": "duration",
            "summary": "Movie\u0020duration\u0020in\u0020seconds.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_duration"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024frameCount",
            "name": "frameCount",
            "summary": "Current\u0020frame\u0020index",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_frameCount"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024frameRate",
            "name": "frameRate",
            "summary": "Movie\u0020frame\u0020rate.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_frameRate"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024comment",
            "name": "comment",
            "summary": "Comment\u0020ID3\u0020field.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_comment"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024title",
            "name": "title",
            "summary": "Title\u0020ID3\u0020field.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_title"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024artist",
            "name": "artist",
            "summary": "Author\u0020ID3\u0020field.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_artist"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024copyright",
            "name": "copyright",
            "summary": "Copyright\u0020ID3\u0020field.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_copyright"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024genre",
            "name": "genre",
            "summary": "Genre\u0020ID3\u0020field.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_genre"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024trackNumber",
            "name": "trackNumber",
            "summary": "Track\u0020ID3\u0020field.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_trackNumber"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024year",
            "name": "year",
            "summary": "Year\u0020ID3\u0020field.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_year"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024frameHeight",
            "name": "frameHeight",
            "summary": "Movie\u0020frame\u0020height.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_frameHeight"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024frameWidth",
            "name": "frameWidth",
            "summary": "Movie\u0020frame\u0020width.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_frameWidth"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024pixelFormat",
            "name": "pixelFormat",
            "summary": "Movie\u0020pixel\u0020format.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_pixelFormat"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024pixelAspectRatio",
            "name": "pixelAspectRatio",
            "summary": "Movie\u0020pixel\u0020aspect\u0020ratio.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_pixelAspectRatio"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024bitRate",
            "name": "bitRate",
            "summary": "Movie\u0020bit\u0020rate\u0020combined\u0020with\u0020audio\u0020bit\u0020rate.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_bitRate"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024videoBitRate",
            "name": "videoBitRate",
            "summary": "Movie\u0020video\u0020stream\u0020bit\u0020rate.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_videoBitRate"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024audioBitRate",
            "name": "audioBitRate",
            "summary": "Movie\u0020audio\u0020stream\u0020bit\u0020rate.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_audioBitRate"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024audioSampleRate",
            "name": "audioSampleRate",
            "summary": "Audio\u0020sample\u0020rate.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_audioSampleRate"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024frameNumber",
            "name": "frameNumber",
            "summary": "Current\u0020frame\u0020number.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_frameNumber"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024videoCodec",
            "name": "videoCodec",
            "summary": "Movie\u0020video\u0020codec.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_videoCodec"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024audioCodec",
            "name": "audioCodec",
            "summary": "Movie\u0020audio\u0020codec.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_audioCodec"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024audioChannels",
            "name": "audioChannels",
            "summary": "Movie\u0020audio\u0020channels.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_audioChannels"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Movie\u003A\u003A\u0024rotation",
            "name": "rotation",
            "summary": "Movie\u0020rotation.",
            "url": "classes/Char0n-FFMpegPHP-Movie.html#property_rotation"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\AbstractProvider",
            "name": "AbstractProvider",
            "summary": "AbstractProvider\u0020parent\u0020of\u0020all\u0020output\u0020providers.",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-AbstractProvider.html"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\AbstractProvider\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Base\u0020constructor\u0020for\u0020every\u0020provider",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-AbstractProvider.html#method___construct"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\AbstractProvider\u003A\u003AsetMovieFile\u0028\u0029",
            "name": "setMovieFile",
            "summary": "Setting\u0020movie\u0020file\u0020path",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-AbstractProvider.html#method_setMovieFile"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\AbstractProvider\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-AbstractProvider.html#method_serialize"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\AbstractProvider\u003A\u003Aunserialize\u0028\u0029",
            "name": "unserialize",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-AbstractProvider.html#method_unserialize"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\AbstractProvider\u003A\u003A\u0024EX_CODE_FILE_NOT_FOUND",
            "name": "EX_CODE_FILE_NOT_FOUND",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-AbstractProvider.html#property_EX_CODE_FILE_NOT_FOUND"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\AbstractProvider\u003A\u003A\u0024persistentBuffer",
            "name": "persistentBuffer",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-AbstractProvider.html#property_persistentBuffer"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\AbstractProvider\u003A\u003A\u0024binary",
            "name": "binary",
            "summary": "Binary\u0020that\u0020returns\u0020info\u0020about\u0020movie\u0020file",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-AbstractProvider.html#property_binary"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\AbstractProvider\u003A\u003A\u0024movieFile",
            "name": "movieFile",
            "summary": "Movie\u0020File\u0020path",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-AbstractProvider.html#property_movieFile"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\AbstractProvider\u003A\u003A\u0024persistent",
            "name": "persistent",
            "summary": "Persistent\u0020functionality\u0020on\/off",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-AbstractProvider.html#property_persistent"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\FFMpegProvider",
            "name": "FFMpegProvider",
            "summary": "FFmpegOutputProvider\u0020ffmpeg\u0020provider\u0020implementation.",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-FFMpegProvider.html"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\FFMpegProvider\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-FFMpegProvider.html#method___construct"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\FFMpegProvider\u003A\u003AgetOutput\u0028\u0029",
            "name": "getOutput",
            "summary": "Getting\u0020parsable\u0020output\u0020from\u0020ffmpeg\u0020binary.",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-FFMpegProvider.html#method_getOutput"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\FFMpegProvider\u003A\u003A\u0024EX_CODE_NO_FFMPEG",
            "name": "EX_CODE_NO_FFMPEG",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-FFMpegProvider.html#property_EX_CODE_NO_FFMPEG"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\FFProbeProvider",
            "name": "FFProbeProvider",
            "summary": "FFProbeProvider\u0020ffprobe\u0020provider\u0020implementation.",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-FFProbeProvider.html"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\FFProbeProvider\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-FFProbeProvider.html#method___construct"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\FFProbeProvider\u003A\u003AgetOutput\u0028\u0029",
            "name": "getOutput",
            "summary": "Getting\u0020parsable\u0020output\u0020from\u0020ffprobe\u0020binary.",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-FFProbeProvider.html#method_getOutput"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\FFProbeProvider\u003A\u003A\u0024EX_CODE_NO_FFPROBE",
            "name": "EX_CODE_NO_FFPROBE",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-FFProbeProvider.html#property_EX_CODE_NO_FFPROBE"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\OutputProvider",
            "name": "OutputProvider",
            "summary": "OutputProvider\u0020interface\u0020of\u0020all\u0020output\u0020providers.",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-OutputProvider.html"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\OutputProvider\u003A\u003AsetMovieFile\u0028\u0029",
            "name": "setMovieFile",
            "summary": "Setting\u0020movie\u0020file\u0020path.",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-OutputProvider.html#method_setMovieFile"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\OutputProvider\u003A\u003AgetOutput\u0028\u0029",
            "name": "getOutput",
            "summary": "Getting\u0020parsable\u0020output.",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-OutputProvider.html#method_getOutput"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\StringProvider",
            "name": "StringProvider",
            "summary": "StringOutputProvider\u0020ffmpeg\u0020provider\u0020implementation.",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-StringProvider.html"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\StringProvider\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "This\u0020class\u0020is\u0020handy\u0020for\u0020testing\u0020purposes.",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-StringProvider.html#method___construct"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\StringProvider\u003A\u003AgetOutput\u0028\u0029",
            "name": "getOutput",
            "summary": "Getting\u0020parsable\u0020output\u0020from\u0020ffmpeg\u0020binary.",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-StringProvider.html#method_getOutput"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\StringProvider\u003A\u003AsetOutput\u0028\u0029",
            "name": "setOutput",
            "summary": "Setting\u0020parsable\u0020output.",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-StringProvider.html#method_setOutput"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders\\StringProvider\u003A\u003A\u0024output",
            "name": "output",
            "summary": "",
            "url": "classes/Char0n-FFMpegPHP-OutputProviders-StringProvider.html#property_output"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\Adapters",
            "name": "Adapters",
            "summary": "",
            "url": "namespaces/char0n-ffmpegphp-adapters.html"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP",
            "name": "FFMpegPHP",
            "summary": "",
            "url": "namespaces/char0n-ffmpegphp.html"
        },                {
            "fqsen": "\\Char0n",
            "name": "Char0n",
            "summary": "",
            "url": "namespaces/char0n.html"
        },                {
            "fqsen": "\\Char0n\\FFMpegPHP\\OutputProviders",
            "name": "OutputProviders",
            "summary": "",
            "url": "namespaces/char0n-ffmpegphp-outputproviders.html"
        }            ]
);
