version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: "daily"
      time: "23:00"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
